### ISSUE TITLE
The new line will be red when enter inerst mode by 'o' or 'O'

### ISSUE THREAD

**Issue by ri-char** [jdhao/whitespace.nvim#1]
The new line will be red when enter inerst mode by 'o' or 'O'.
![image](https://user-images.githubusercontent.com/17962023/177555345-33fdc156-8d9a-4766-a97b-d557c6596557.png)

Related line: https://github.com/jdhao/whitespace.nvim/blob/6157f8d23589bbf11f32758477272f83e37e9a81/autoload/trailing_whitespace.vim#L58

**Comment by jdhao** [comment]
I have also observed this issue sometimes.  However, I have no idea how to fix this currently. 😂
